#requires -version 5.1

<#
Legacy Spec Factory
Copyright 2026 Leo L Zhang

Original author: Leo L Zhang
License: Apache License 2.0
#>

# Small, dependency-free readers used by the native PowerShell contract
# validator. The YAML reader intentionally supports the generated sidecar
# subset needed by this skill; it is not a general-purpose YAML parser.

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

$RlogPattern = '\bRLOG-[A-Z0-9_#$@-]+-\d{3}\b'
$PlaceholderPatterns = @(
    '\bpending reader-oriented summary\b',
    '\bpending semantic deep-read\b',
    '\bpending semantic detail\b',
    '\bplaceholder content\b',
    '\bplaceholder\b',
    '\bnot-yet-deep-read\b',
    '\bnot deep-read\b'
)
$SemanticSeedPatterns = @(
    '\bBatch seed generated by\s+`?index_rpg_source\.py`?',
    '\bpending semantic deep-read\b',
    '\bpending semantic detail\b',
    '\bpending_deep_read\b',
    '\bsemantic(?:_|\s+)status\s*:\s*`?pending_deep_read`?\b',
    '\b(?:execution trigger|step-by-step logic)\s*:\s*pending deep read\b',
    '\bRLOG\s+pending\b'
)

function Read-Utf8Text {
    param([string]$Path)
    return [IO.File]::ReadAllText($Path, [Text.Encoding]::UTF8)
}

function ConvertFrom-SimpleYamlScalar {
    param([string]$Value)

    if ($null -eq $Value) { return '' }
    $clean = $Value.Trim()
    if ($clean.Length -ge 2) {
        if ($clean[0] -eq '"' -and $clean[$clean.Length - 1] -eq '"') {
            $clean = $clean.Substring(1, $clean.Length - 2)
            $clean = $clean.Replace('\"', '"').Replace('\\', '\')
        }
        elseif ($clean[0] -eq "'" -and $clean[$clean.Length - 1] -eq "'") {
            $clean = $clean.Substring(1, $clean.Length - 2).Replace("''", "'")
        }
    }
    return $clean
}

function Get-YamlLines {
    param([string]$Path)
    return @(Read-Utf8Text $Path -split "`r?`n")
}

function Get-Indent {
    param([string]$Line)
    return $Line.Length - $Line.TrimStart(' ').Length
}

function Find-YamlSection {
    param(
        [string[]]$Lines,
        [string]$Key,
        [int]$StartIndex = 0,
        [int]$EndIndex = -1
    )

    if ($EndIndex -lt 0) { $EndIndex = $Lines.Count }
    for ($index = $StartIndex; $index -lt $EndIndex; $index++) {
        if ($Lines[$index] -match ('^\s*' + [regex]::Escape($Key) + ':\s*(?:#.*)?$')) {
            $indent = Get-Indent $Lines[$index]
            $sectionEnd = $EndIndex
            for ($cursor = $index + 1; $cursor -lt $EndIndex; $cursor++) {
                $candidate = $Lines[$cursor]
                if ($candidate.Trim().Length -eq 0 -or $candidate.TrimStart().StartsWith('#')) { continue }
                if ((Get-Indent $candidate) -le $indent) {
                    $sectionEnd = $cursor
                    break
                }
            }
            return [pscustomobject]@{ Start = $index; End = $sectionEnd; Indent = $indent }
        }
    }
    return $null
}

function Get-YamlRootScalar {
    param([string[]]$Lines, [string]$Key)

    foreach ($line in $Lines) {
        if ((Get-Indent $line) -eq 0 -and $line -match ('^' + [regex]::Escape($Key) + ':\s*(.*?)\s*$')) {
            return ConvertFrom-SimpleYamlScalar $Matches[1]
        }
    }
    return ''
}

function Get-YamlNestedScalar {
    param([string[]]$Lines, [string]$ParentKey, [string]$Key)

    $parent = Find-YamlSection $Lines $ParentKey
    if ($null -eq $parent) { return '' }
    for ($index = $parent.Start + 1; $index -lt $parent.End; $index++) {
        $line = $Lines[$index]
        if ($line -match ('^\s*' + [regex]::Escape($Key) + ':\s*(.*?)\s*$')) {
            return ConvertFrom-SimpleYamlScalar $Matches[1]
        }
    }
    return ''
}

function Get-SidecarEntries {
    param([string]$SummaryPath)

    $entries = @{}
    $lines = Get-YamlLines $SummaryPath
    $sidecars = Find-YamlSection $lines 'sidecars'
    if ($null -eq $sidecars) { return $entries }
    $entryIndent = $sidecars.Indent + 2
    $currentKey = $null
    for ($index = $sidecars.Start + 1; $index -lt $sidecars.End; $index++) {
        $line = $lines[$index]
        if ($line.Trim().Length -eq 0 -or $line.TrimStart().StartsWith('#')) { continue }
        $indent = Get-Indent $line
        if ($indent -eq $entryIndent -and $line -match '^\s*([A-Za-z0-9_-]+):\s*$') {
            $currentKey = $Matches[1]
            $entries[$currentKey] = @{ path = ''; status = '' }
            continue
        }
        if ($null -ne $currentKey -and $indent -gt $entryIndent -and $line -match '^\s*(path|status):\s*(.*?)\s*$') {
            $entries[$currentKey][$Matches[1]] = ConvertFrom-SimpleYamlScalar $Matches[2]
        }
    }
    return $entries
}

function Get-YamlListMappings {
    param([string]$Path, [string]$RootKey, [string]$ListKey)

    $lines = Get-YamlLines $Path
    $root = Find-YamlSection $lines $RootKey
    if ($null -eq $root) { return @() }
    $list = Find-YamlSection $lines $ListKey ($root.Start + 1) $root.End
    if ($null -eq $list) { return @() }

    $entries = New-Object System.Collections.ArrayList
    $current = $null
    $nestedKey = $null
    $nestedIndent = -1
    $entryIndent = $list.Indent + 2
    for ($index = $list.Start + 1; $index -lt $list.End; $index++) {
        $line = $lines[$index]
        if ($line.Trim().Length -eq 0 -or $line.TrimStart().StartsWith('#')) { continue }
        $indent = Get-Indent $line
        if ($indent -eq $entryIndent -and $line -match '^\s*-\s*(.*)$') {
            if ($null -ne $current) { [void]$entries.Add($current) }
            $current = @{}
            $nestedKey = $null
            $nestedIndent = -1
            $inline = $Matches[1]
            if ($inline -match '^([A-Za-z0-9_-]+):\s*(.*?)\s*$') {
                $current[$Matches[1]] = ConvertFrom-SimpleYamlScalar $Matches[2]
            }
            continue
        }
        if ($null -ne $current -and $indent -gt $entryIndent -and $line -match '^\s*([A-Za-z0-9_-]+):\s*(.*?)\s*$') {
            $key = $Matches[1]
            $value = $Matches[2]
            if ($value -ne '') {
                $current[$key] = ConvertFrom-SimpleYamlScalar $value
                $nestedKey = $null
                $nestedIndent = -1
            }
            else {
                $current[$key] = @()
                $nestedKey = $key
                $nestedIndent = $indent
            }
            continue
        }
        if ($null -ne $current -and $null -ne $nestedKey -and
            $indent -gt $nestedIndent -and $line -match '^\s*-\s*(.*?)\s*$') {
            $current[$nestedKey] = @($current[$nestedKey]) + @(ConvertFrom-SimpleYamlScalar $Matches[1])
        }
    }
    if ($null -ne $current) { [void]$entries.Add($current) }
    return @($entries.ToArray())
}

function Get-RlogIdsFromYaml {
    param([string]$Path)

    $ids = New-Object System.Collections.ArrayList
    foreach ($detail in @(Get-YamlListMappings $Path 'routine_logic_inventory' 'details')) {
        if ($detail.ContainsKey('detail_id') -and [string]$detail.detail_id -ne '') {
            [void]$ids.Add(([string]$detail.detail_id).ToUpperInvariant())
        }
    }
    return @($ids.ToArray())
}

function Get-MessageEntries {
    param([string]$Path)

    $details = @(Get-YamlListMappings $Path 'message_inventory' 'details')
    if ($details.Count -gt 0) { return $details }
    return @(Get-YamlListMappings $Path 'message_inventory' 'summary')
}

function Get-HeadingMatches {
    param([string]$Markdown, [bool]$H2Only = $false)
    $pattern = if ($H2Only) { '(?m)^##\s+(.+?)\s*$' } else { '(?m)^#{2,6}\s+(.+?)\s*$' }
    return @([regex]::Matches($Markdown, $pattern))
}

function Get-HeadingMap {
    param([string]$Markdown, [bool]$H2Only = $false)

    $positions = @{}
    foreach ($match in @(Get-HeadingMatches $Markdown $H2Only)) {
        $heading = $match.Groups[1].Value.Trim()
        if (-not $positions.ContainsKey($heading)) { $positions[$heading] = $match.Index }
    }
    return $positions
}

function Get-H2SectionText {
    param([string]$Markdown, [string]$Heading)

    $matches = @(Get-HeadingMatches $Markdown $true)
    for ($index = 0; $index -lt $matches.Count; $index++) {
        if ($matches[$index].Groups[1].Value.Trim() -ne $Heading) { continue }
        $start = $matches[$index].Index + $matches[$index].Length
        $end = if ($index + 1 -lt $matches.Count) { $matches[$index + 1].Index } else { $Markdown.Length }
        return $Markdown.Substring($start, $end - $start)
    }
    return ''
}

function Get-H3Blocks {
    param([string]$SectionText)

    $matches = @([regex]::Matches($SectionText, '(?m)^###\s+(.+?)\s*$'))
    $blocks = New-Object System.Collections.ArrayList
    for ($index = 0; $index -lt $matches.Count; $index++) {
        $start = $matches[$index].Index + $matches[$index].Length
        $end = if ($index + 1 -lt $matches.Count) { $matches[$index + 1].Index } else { $SectionText.Length }
        [void]$blocks.Add([pscustomobject]@{
            Heading = $matches[$index].Groups[1].Value.Trim()
            Position = $matches[$index].Index
            Body = $SectionText.Substring($start, $end - $start)
        })
    }
    return @($blocks.ToArray())
}

function Test-ReaderFirstPlaceholder {
    param([string]$Text)
    foreach ($pattern in $PlaceholderPatterns) {
        if ([regex]::IsMatch($Text, $pattern, [Text.RegularExpressions.RegexOptions]::IgnoreCase)) { return $true }
    }
    return $false
}

function Get-MeaningfulWordCount {
    param([string]$Text)

    $cleaned = [regex]::Replace($Text, '`[^`]*`', ' ')
    $cleaned = [regex]::Replace($cleaned, $RlogPattern, ' ', [Text.RegularExpressions.RegexOptions]::IgnoreCase)
    $cleaned = [regex]::Replace($cleaned, '\bSR\d{3,}\b', ' ', [Text.RegularExpressions.RegexOptions]::IgnoreCase)
    return [regex]::Matches($cleaned, '[A-Za-z0-9][A-Za-z0-9_#$@/-]*|[\u4e00-\u9fff]{2,}').Count
}

function Get-TableCellsOrLine {
    param([string]$Line)

    $stripped = $Line.Trim()
    if ($stripped -eq '') { return @() }
    if ($stripped.StartsWith('|') -and $stripped.EndsWith('|')) {
        $cells = New-Object System.Collections.ArrayList
        foreach ($cell in $stripped.Trim('|').Split('|')) {
            $value = $cell.Trim()
            if ($value -ne '' -and $value -notmatch '^:?-{3,}:?$') { [void]$cells.Add($value) }
        }
        return @($cells.ToArray())
    }
    return @($stripped)
}

function Get-MarkdownTableRows {
    param([string]$SectionText)

    $rows = New-Object System.Collections.ArrayList
    foreach ($line in ($SectionText -split "`r?`n")) {
        $stripped = $line.Trim()
        if (-not ($stripped.StartsWith('|') -and $stripped.EndsWith('|'))) { continue }
        $cells = @($stripped.Trim('|').Split('|') | ForEach-Object { $_.Trim() })
        $separator = $cells.Count -gt 0
        foreach ($cell in $cells) {
            if ($cell -notmatch '^:?-{3,}:?$') { $separator = $false; break }
        }
        if (-not $separator) {
            [void]$rows.Add([pscustomobject]@{ Cells = $cells })
        }
    }
    return @($rows.ToArray())
}

function Get-RlogIdsFromText {
    param([string]$Text)
    return @([regex]::Matches($Text, $RlogPattern, [Text.RegularExpressions.RegexOptions]::IgnoreCase) |
        ForEach-Object { $_.Value.ToUpperInvariant() })
}

function Get-UniqueSorted {
    param([object[]]$Values)
    return @($Values | Sort-Object -Unique)
}

function Compare-StringSets {
    param([string[]]$Left, [string[]]$Right)
    return @(Get-UniqueSorted @($Left | Where-Object { $Right -notcontains $_ }))
}

function Test-SequenceEqual {
    param([object[]]$Left, [object[]]$Right)
    if ($Left.Count -ne $Right.Count) { return $false }
    for ($index = 0; $index -lt $Left.Count; $index++) {
        if ([string]$Left[$index] -ne [string]$Right[$index]) { return $false }
    }
    return $true
}

function Get-SemanticSeedMatches {
    param([string]$Text)

    $matches = New-Object System.Collections.ArrayList
    foreach ($pattern in $SemanticSeedPatterns) {
        if ([regex]::IsMatch($Text, $pattern, [Text.RegularExpressions.RegexOptions]::IgnoreCase)) {
            [void]$matches.Add($pattern.Replace('\b', ''))
        }
    }
    return @($matches.ToArray())
}

function Find-RoutineArtifactPath {
    param([string]$AnalysisDir, [string]$BaseName)

    $generic = Join-Path $AnalysisDir $BaseName
    if (Test-Path -LiteralPath $generic -PathType Leaf) { return $generic }
    $matches = @(Get-ChildItem -LiteralPath $AnalysisDir -Filter "*-$BaseName" -File -ErrorAction SilentlyContinue)
    if ($matches.Count -eq 1) { return $matches[0].FullName }
    return $null
}

function Get-RlogSemanticQualityFindings {
    param(
        [string]$Markdown,
        [AllowNull()][string[]]$ExpectedIds,
        [string]$ArtifactLabel
    )

    $matches = @([regex]::Matches(
        $Markdown,
        '(?im)^#{2,6}\s+(RLOG-[A-Z0-9_#$@-]+-\d{3})\b.*$'
    ))
    $blocks = @{}
    for ($index = 0; $index -lt $matches.Count; $index++) {
        $start = $matches[$index].Index + $matches[$index].Length
        $end = if ($index + 1 -lt $matches.Count) { $matches[$index + 1].Index } else { $Markdown.Length }
        $blocks[$matches[$index].Groups[1].Value.ToUpperInvariant()] = $Markdown.Substring($start, $end - $start)
    }
    if ($null -eq $ExpectedIds -and $blocks.Count -eq 0) {
        return @("$ArtifactLabel Routine Details has no RLOG semantic detail blocks")
    }
    $ids = if ($null -eq $ExpectedIds) { @($blocks.Keys | Sort-Object) } else { @($ExpectedIds) }
    $findings = New-Object System.Collections.ArrayList
    foreach ($rlogId in $ids) {
        if (-not $blocks.ContainsKey($rlogId)) {
            [void]$findings.Add("$ArtifactLabel missing reader-useful detail heading/body for $rlogId")
            continue
        }
        $body = [string]$blocks[$rlogId]
        if (@(Get-SemanticSeedMatches $body).Count -gt 0 -or (Get-MeaningfulWordCount $body) -lt 12) {
            [void]$findings.Add("$ArtifactLabel $rlogId needs reader-useful source-backed semantic detail")
        }
    }
    return @($findings.ToArray())
}

function Get-PendingCoreTableFindings {
    param(
        [string]$BatchText,
        [string]$BatchLabel,
        [string[]]$SectionNames
    )

    $findings = New-Object System.Collections.ArrayList
    foreach ($sectionName in $SectionNames) {
        $rows = @(Get-MarkdownTableRows (Get-H2SectionText $BatchText $sectionName))
        for ($rowIndex = 1; $rowIndex -lt $rows.Count; $rowIndex++) {
            for ($columnIndex = 0; $columnIndex -lt $rows[$rowIndex].Cells.Count; $columnIndex++) {
                $cell = ([string]$rows[$rowIndex].Cells[$columnIndex]).Trim()
                if ($cell -match '^(?:\*\*|`)?pending(?:\*\*|`)?$') {
                    [void]$findings.Add(
                        "$BatchLabel $sectionName contains an unresolved pending table cell " +
                        "in data row $rowIndex, column $($columnIndex + 1)"
                    )
                }
            }
        }
    }
    return @($findings.ToArray())
}

function Test-StructuredSemanticValue {
    param($Value, [int]$MinimumWords = 2)

    if ($null -eq $Value) { return $false }
    $text = if ($Value -is [System.Array]) { @($Value) -join ' ' } else { [string]$Value }
    if ([string]::IsNullOrWhiteSpace($text)) { return $false }
    return @(Get-SemanticSeedMatches $text).Count -eq 0 -and
        (Get-MeaningfulWordCount $text) -ge $MinimumWords
}

function Get-BatchCoverageColumnIds {
    param(
        [string]$BatchText,
        [string[]]$AcceptedHeaders,
        [string]$IdPattern
    )

    $rows = @(Get-MarkdownTableRows (Get-H2SectionText $BatchText 'Batch Coverage Summary'))
    if ($rows.Count -eq 0) { return @() }
    $column = -1
    for ($index = 0; $index -lt $rows[0].Cells.Count; $index++) {
        $header = ([regex]::Replace([string]$rows[0].Cells[$index], '[*_`]', '')).Trim().ToLowerInvariant()
        if ($header -in $AcceptedHeaders) { $column = $index; break }
    }
    if ($column -lt 0) { return @() }
    $identifiers = New-Object System.Collections.ArrayList
    for ($rowIndex = 1; $rowIndex -lt $rows.Count; $rowIndex++) {
        if ($column -ge $rows[$rowIndex].Cells.Count) { continue }
        foreach ($match in [regex]::Matches(
            [string]$rows[$rowIndex].Cells[$column],
            $IdPattern,
            [Text.RegularExpressions.RegexOptions]::IgnoreCase
        )) {
            [void]$identifiers.Add($match.Value.ToUpperInvariant())
        }
    }
    return @(Get-UniqueSorted @($identifiers.ToArray()))
}

function Get-BatchAssignedRlogIds {
    param([string]$BatchText)

    $coverageIds = @(Get-BatchCoverageColumnIds $BatchText @('rlog detail', 'rlog', 'detail link') $script:RlogPattern)
    $routineSection = Get-H2SectionText $BatchText 'Routine Details'
    $detailIds = @([regex]::Matches($routineSection, '(?im)^#{2,6}\s+(RLOG-[A-Z0-9_#$@-]+-\d{3})\b') |
        ForEach-Object { $_.Groups[1].Value.ToUpperInvariant() })
    return @(Get-UniqueSorted @($coverageIds + $detailIds))
}

function Get-BatchAssignedWindowIds {
    param([string]$BatchText)

    return @(Get-BatchCoverageColumnIds $BatchText @(
        'window id', 'deep-read window', 'deep read window'
    ) '\bDRW-[A-Z0-9_#$@-]+-\d{3}\b')
}

function Get-BatchYamlSemanticCompletionFindings {
    param([string]$AnalysisDir, [object[]]$BatchFiles)

    if ($BatchFiles.Count -eq 0) { return @() }
    $yamlPath = Find-RoutineArtifactPath $AnalysisDir 'routine-logic-details.yaml'
    if (-not $yamlPath) { return @() }
    $detailsById = @{}
    foreach ($entry in @(Get-YamlListMappings $yamlPath 'routine_logic_inventory' 'details')) {
        if ($entry.ContainsKey('detail_id') -and [string]$entry.detail_id -ne '') {
            $detailsById[([string]$entry.detail_id).ToUpperInvariant()] = $entry
        }
    }
    $summaryById = @{}
    foreach ($entry in @(Get-YamlListMappings $yamlPath 'routine_logic_inventory' 'summary')) {
        if ($entry.ContainsKey('detail_ref') -and [string]$entry.detail_ref -ne '') {
            $summaryById[([string]$entry.detail_ref).ToUpperInvariant()] = $entry
        }
    }
    $assigned = New-Object System.Collections.ArrayList
    foreach ($batch in $BatchFiles) {
        foreach ($rlogId in @(Get-BatchAssignedRlogIds (Read-Utf8Text $batch.FullName))) {
            [void]$assigned.Add($rlogId)
        }
    }
    $structuredFields = @(
        'step_by_step_logic', 'field_calculations',
        'conditioned_calculation_blocks', 'outcome_reverse_traces',
        'field_lineage', 'branch_outcomes', 'routine_exception_closure'
    )
    $findings = New-Object System.Collections.ArrayList
    foreach ($rlogId in @(Get-UniqueSorted @($assigned.ToArray()))) {
        if (-not $detailsById.ContainsKey($rlogId)) {
            [void]$findings.Add("$(Split-Path $yamlPath -Leaf) missing details[] semantic record for batched $rlogId")
            continue
        }
        $detail = $detailsById[$rlogId]
        $status = if ($detail.ContainsKey('semantic_status')) { ([string]$detail.semantic_status).Trim().ToLowerInvariant() } else { '' }
        $coverage = if ($detail.ContainsKey('coverage')) { ([string]$detail.coverage).Trim().ToLowerInvariant() } else { '' }
        if ($status -ne 'deep_read_complete') {
            $actual = if ($status -ne '') { $status } else { 'missing' }
            [void]$findings.Add("$(Split-Path $yamlPath -Leaf) batched $rlogId requires semantic_status: deep_read_complete, found $actual")
        }
        if ($coverage -ne 'deep_read') {
            $actual = if ($coverage -ne '') { $coverage } else { 'missing' }
            [void]$findings.Add("$(Split-Path $yamlPath -Leaf) batched $rlogId requires coverage: deep_read, found $actual")
        }
        if (-not $detail.ContainsKey('execution_trigger') -or
            -not (Test-StructuredSemanticValue $detail.execution_trigger 3)) {
            [void]$findings.Add("$(Split-Path $yamlPath -Leaf) batched $rlogId needs a source-backed execution_trigger")
        }
        $incomplete = @($structuredFields | Where-Object {
            -not $detail.ContainsKey($_) -or -not (Test-StructuredSemanticValue $detail[$_])
        })
        if ($incomplete.Count -gt 0) {
            [void]$findings.Add(
                "$(Split-Path $yamlPath -Leaf) batched $rlogId has incomplete structured semantic field(s): " +
                ($incomplete -join ', ')
            )
        }
        if (-not $summaryById.ContainsKey($rlogId)) {
            [void]$findings.Add("$(Split-Path $yamlPath -Leaf) missing summary[] mirror for batched $rlogId")
            continue
        }
        $summary = $summaryById[$rlogId]
        $summaryStatus = if ($summary.ContainsKey('semantic_status')) { ([string]$summary.semantic_status).Trim().ToLowerInvariant() } else { '' }
        $summaryCoverage = if ($summary.ContainsKey('coverage')) { ([string]$summary.coverage).Trim().ToLowerInvariant() } else { '' }
        if ($summaryStatus -ne $status -or $summaryCoverage -ne $coverage) {
            [void]$findings.Add("$(Split-Path $yamlPath -Leaf) summary[] and details[] semantic state disagree for batched $rlogId")
        }
    }
    return @($findings.ToArray())
}

function Get-RoutineSemanticCompletionFindings {
    param([string]$AnalysisDir)

    $findings = New-Object System.Collections.ArrayList
    $markdownPath = Find-RoutineArtifactPath $AnalysisDir 'routine-logic-details.md'
    $yamlPath = Find-RoutineArtifactPath $AnalysisDir 'routine-logic-details.yaml'
    if ($markdownPath) {
        $markdown = Read-Utf8Text $markdownPath
        $seedMatches = @(Get-SemanticSeedMatches $markdown)
        if ($seedMatches.Count -gt 0) {
            [void]$findings.Add(
                "$(Split-Path $markdownPath -Leaf) still contains pending semantic deep-read content; " +
                'replace the indexer seed with source-backed routine detail. Matched: ' +
                ($seedMatches -join ', ')
            )
        }
        $expectedIds = if ($yamlPath) { @(Get-RlogIdsFromYaml $yamlPath) } else { $null }
        $routineSection = Get-H2SectionText $markdown 'Routine Details'
        if ($routineSection -eq '') { $routineSection = $markdown }
        foreach ($finding in @(Get-RlogSemanticQualityFindings $routineSection $expectedIds (Split-Path $markdownPath -Leaf))) {
            [void]$findings.Add($finding)
        }
    }
    if ($yamlPath) {
        $pendingRefs = New-Object System.Collections.ArrayList
        $pendingMarkers = New-Object System.Collections.ArrayList
        foreach ($collection in @('summary', 'details')) {
            foreach ($entry in @(Get-YamlListMappings $yamlPath 'routine_logic_inventory' $collection)) {
                $status = if ($entry.ContainsKey('semantic_status')) { ([string]$entry.semantic_status).Trim().ToLowerInvariant() } else { '' }
                $seedText = ''
                foreach ($key in @('execution_trigger', 'unresolved_routine_logic')) {
                    if ($entry.ContainsKey($key)) { $seedText += ' ' + [string]$entry[$key] }
                }
                if ($status -in @('pending', 'pending_deep_read', 'indexed_only') -or $seedText -match '\bpending deep read\b') {
                    $marker = if ($status -ne '') { $status } else { 'pending_deep_read' }
                    [void]$pendingMarkers.Add($marker)
                    $reference = 'unknown routine'
                    foreach ($key in @('detail_id', 'detail_ref', 'routine')) {
                        if ($entry.ContainsKey($key) -and [string]$entry[$key] -ne '') { $reference = [string]$entry[$key]; break }
                    }
                    [void]$pendingRefs.Add($reference)
                }
            }
        }
        $uniqueRefs = @(Get-UniqueSorted @($pendingRefs.ToArray()))
        if ($uniqueRefs.Count -gt 0) {
            $markers = @(Get-UniqueSorted @($pendingMarkers.ToArray())) -join ', '
            [void]$findings.Add(
                "$(Split-Path $yamlPath -Leaf) retains incomplete semantic status marker(s) " +
                "${markers} for: " + ($uniqueRefs -join ', ')
            )
        }
    }
    return @($findings.ToArray())
}

Export-ModuleMember -Function @(
    'Read-Utf8Text',
    'Get-YamlLines',
    'Get-YamlRootScalar',
    'Get-YamlNestedScalar',
    'Get-SidecarEntries',
    'Get-RlogIdsFromYaml',
    'Get-MessageEntries',
    'Get-SemanticSeedMatches',
    'Get-RlogSemanticQualityFindings',
    'Get-PendingCoreTableFindings',
    'Get-BatchAssignedRlogIds',
    'Get-BatchYamlSemanticCompletionFindings',
    'Get-RoutineSemanticCompletionFindings',
    'Find-RoutineArtifactPath',
    'Get-HeadingMap',
    'Get-H2SectionText',
    'Get-H3Blocks',
    'Test-ReaderFirstPlaceholder',
    'Get-MeaningfulWordCount',
    'Get-TableCellsOrLine',
    'Get-MarkdownTableRows',
    'Get-RlogIdsFromText',
    'Get-UniqueSorted',
    'Compare-StringSets',
    'Test-SequenceEqual'
)
