#!/usr/bin/env python3
"""Validate program-list batch status files and completed output folders."""

from __future__ import annotations

import argparse
import csv
import importlib.util
import re
import sys
from pathlib import Path
from typing import Any


ALLOWED_STATUSES = {
    "queued",
    "in_progress",
    "completed",
    "completed_with_warnings",
    "scanned_unvalidated",
    "blocked_missing_source",
    "failed_validator",
    "failed_runtime",
    "skipped_not_program",
}

REQUIRED_ARTIFACT_BASE_NAMES = {
    "program-analysis.md",
    "source-index.yaml",
    "program-analysis-summary.yaml",
    "routine-index.md",
    "message-inventory.yaml",
    "routine-logic-details.md",
    "routine-logic-details.yaml",
}

ARTIFACT_REQUIRED_STATUSES = {"completed", "completed_with_warnings", "scanned_unvalidated"}
# `scanned_unvalidated` is a valid deferred checkpoint, but never a terminal
# batch close: it deliberately skipped the semantic final validator.
NON_TERMINAL_STATUSES = {"queued", "in_progress", "scanned_unvalidated"}
ARTIFACT_SAFE_RE = re.compile(r'[\s<>:"/\\|?*]+')
SCAFFOLD_TEXT_BASE_NAMES = ("program-analysis.md", "routine-logic-details.md")
SCAFFOLD_PATTERNS = (
    re.compile(r"\bDraft wrapper seed generated\b", re.I),
    re.compile(r"\bpending reader-oriented summary\b", re.I),
    re.compile(r"\bpending semantic deep-read\b", re.I),
    re.compile(r"\bpending semantic detail\b", re.I),
    re.compile(r"\breplace this placeholder\b", re.I),
    re.compile(r"\bplaceholder content\b", re.I),
    re.compile(r"\bnot-yet-deep-read\b", re.I),
)
RETAINED_SEMANTIC_PATTERNS = SCAFFOLD_PATTERNS + (
    re.compile(r"\bBatch seed generated by\s+`?index_rpg_source\.py`?", re.I),
    re.compile(r"\bpending_deep_read\b", re.I),
    re.compile(r"\bsemantic(?:_|\s+)status\s*:\s*`?pending_deep_read`?\b", re.I),
    re.compile(
        r"\bsemantic_status[ \t]*:[ \t]*[\"']?indexed_only[\"']?"
        r"[ \t]*(?:#.*)?(?:\r?\n|$)",
        re.I,
    ),
    re.compile(
        r"\b(?:execution_trigger|unresolved_routine_logic)[ \t]*:[ \t]*"
        r"[\"']?pending deep read[\"']?[ \t]*(?:#.*)?(?:\r?\n|$)",
        re.I,
    ),
    re.compile(r"\b(?:execution trigger|step-by-step logic)\s*:\s*pending deep read\b", re.I),
    re.compile(r"\bRLOG\s+pending\b", re.I),
    re.compile(r"\|\s*(?:`|\*\*)?pending(?:`|\*\*)?\s*\|", re.I),
)

_UPSTREAM_VALIDATOR: Any | None = None

READER_FIRST_LAYOUT_GROUPS = (
    ("Program Reading Summary", ("## Program Reading Summary",)),
    ("Calculation Logic", ("## Calculation Logic",)),
    ("Calculation Logic Overview", ("### Calculation Logic Overview",)),
    (
        "Routine Index For Calculation Logic",
        ("### Routine Index For Calculation Logic",),
    ),
    ("Validation Logic", ("## Validation Logic",)),
    ("Validation Logic Overview", ("### Validation Logic Overview",)),
    (
        "Routine Index For Validation Logic",
        ("### Routine Index For Validation Logic",),
    ),
    ("Exception Handling", ("## Exception Handling",)),
    (
        "Exception Handling Overview",
        ("### Exception Flow Overview", "### Exception Handling Overview"),
    ),
    (
        "Routine Index For Exception Handling",
        ("### Routine Index For Exception Handling",),
    ),
)


def artifact_program_prefix(program_name: str) -> str:
    prefix = ARTIFACT_SAFE_RE.sub("_", program_name.strip().upper())
    prefix = prefix.strip("._-")
    return prefix or "PROGRAM"


def required_artifacts_for_member(member: str) -> set[str]:
    prefix = artifact_program_prefix(member)
    return {f"{prefix}-{base_name}" for base_name in REQUIRED_ARTIFACT_BASE_NAMES}


def required_artifact_for_member(member: str, base_name: str) -> str:
    return f"{artifact_program_prefix(member)}-{base_name}"


def upstream_program_validator() -> Any:
    """Load the canonical per-program terminal validator once per batch check."""

    global _UPSTREAM_VALIDATOR
    if _UPSTREAM_VALIDATOR is not None:
        return _UPSTREAM_VALIDATOR
    validator_path = (
        Path(__file__).resolve().parents[2]
        / "legacy-ibmi-program-analyzer"
        / "scripts"
        / "validate_program_analysis_contract.py"
    )
    spec = importlib.util.spec_from_file_location(
        "legacy_ibmi_program_analysis_contract_for_batch_status", validator_path
    )
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load upstream program validator: {validator_path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules.setdefault(spec.name, module)
    spec.loader.exec_module(module)
    _UPSTREAM_VALIDATOR = module
    return module


def upstream_contract_findings(
    output_path: Path,
    expected_size_tier: str | None = None,
    expected_source_index_sha256: str | None = None,
    expected_execution_plan_sha256: str | None = None,
) -> list[str]:
    """Run the semantic finalization contract for a claimed completed row."""

    try:
        return [
            str(item)
            for item in upstream_program_validator().validate(
                output_path,
                expected_size_tier=expected_size_tier,
                expected_source_index_sha256=expected_source_index_sha256,
                expected_execution_plan_sha256=expected_execution_plan_sha256,
            )
        ]
    except Exception as exc:  # pragma: no cover - defensive runtime reporting
        return [f"could not run upstream program-analysis contract validator: {exc}"]


def scaffold_patterns_in(
    text: str,
    patterns: tuple[re.Pattern[str], ...] = SCAFFOLD_PATTERNS,
) -> list[str]:
    return [pattern.pattern.replace("\\b", "") for pattern in patterns if pattern.search(text)]


def reader_first_layout_findings(text: str) -> list[str]:
    """Check the cheap, non-semantic front-loaded layout contract.

    Deferred validation intentionally skips the full program analyzer
    validator, but it must still prevent a semantic rewrite from deleting the
    SME-facing navigation headings that make the main artifact readable.
    """

    positions: list[tuple[str, int]] = []
    missing: list[str] = []
    for label, candidates in READER_FIRST_LAYOUT_GROUPS:
        match = None
        for candidate in candidates:
            match = re.search(rf"(?m)^{re.escape(candidate)}\s*$", text)
            if match:
                break
        if match is None:
            missing.append(label)
        else:
            positions.append((label, match.start()))

    findings: list[str] = []
    if missing:
        findings.append(
            "program-analysis.md missing reader-first layout heading(s): "
            + ", ".join(missing)
        )

    if len(positions) == len(READER_FIRST_LAYOUT_GROUPS):
        out_of_order = [
            f"{previous} before {current}"
            for (previous, previous_position), (current, current_position) in zip(
                positions, positions[1:]
            )
            if previous_position >= current_position
        ]
        if out_of_order:
            findings.append(
                "program-analysis.md reader-first layout headings are out of order: "
                + "; ".join(out_of_order)
            )
    return findings


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return [
            {key: (value or "").strip() for key, value in row.items() if key is not None}
            for row in csv.DictReader(handle)
        ]


def manifest_top_level_value(path: Path, key: str) -> str:
    if not path.is_file():
        return ""
    pattern = re.compile(rf"(?m)^{re.escape(key)}:\s*(.*?)\s*$")
    match = pattern.search(path.read_text(encoding="utf-8-sig"))
    if match is None:
        return ""
    return match.group(1).strip().strip('"\'')


def manifest_subagent_expected_count(
    path: Path,
    rows: list[dict[str, str]],
) -> tuple[int, str | None]:
    actual_count = sum(1 for row in rows if row.get("subagent_prompt_path", "").strip())
    value = manifest_top_level_value(path, "subagent_expected_count")
    if not value:
        return actual_count, None
    try:
        manifest_count = int(value)
    except ValueError:
        return actual_count, "Kiro/parallel batch has invalid subagent_expected_count in manifest"
    if manifest_count < 0:
        return actual_count, "Kiro/parallel batch has negative subagent_expected_count in manifest"
    if manifest_count != actual_count:
        return max(manifest_count, actual_count), (
            "Kiro/parallel batch subagent_expected_count does not match "
            "the status-list worker prompt count"
        )
    return actual_count, None


def manifest_program_execution_locks(path: Path) -> dict[str, dict[str, str]]:
    """Return the precreated large-program hashes frozen in the batch manifest."""

    if not path.is_file():
        return {}
    try:
        import yaml  # type: ignore
    except ImportError:
        return {}
    try:
        payload = yaml.safe_load(path.read_text(encoding="utf-8-sig"))
    except yaml.YAMLError:
        return {}
    if not isinstance(payload, dict):
        return {}
    locks: dict[str, dict[str, str]] = {}
    for item in payload.get("programs", []) or []:
        if not isinstance(item, dict):
            continue
        member = str(item.get("member") or "").strip().upper()
        if not member:
            continue
        locks[member] = {
            "source_index_sha256": str(item.get("source_index_sha256") or "").strip(),
            "deep_read_execution_plan_path": str(
                item.get("deep_read_execution_plan_path") or ""
            ).strip(),
            "deep_read_execution_plan_sha256": str(
                item.get("deep_read_execution_plan_sha256") or ""
            ).strip(),
        }
    return locks


def resolve_output_dir(value: str, delivery_root: Path | None) -> Path | None:
    if not value or "<delivery-root>" in value:
        return None
    path = Path(value)
    if path.is_absolute():
        return path
    if delivery_root:
        return delivery_root / path
    return path


def retained_semantic_artifacts(output_path: Path, member: str) -> list[Path]:
    artifacts = [
        output_path / required_artifact_for_member(member, "routine-logic-details.yaml")
    ]
    batch_dir = output_path / "routine-logic-details"
    if batch_dir.is_dir():
        artifacts.extend(batch_dir.rglob("*.md"))
    return sorted({path for path in artifacts if path.is_file()})


def validate(args: argparse.Namespace) -> int:
    batch_dir = Path(args.batch_dir).resolve()
    status_path = Path(args.status_list).resolve() if args.status_list else batch_dir / "program-list-status.csv"
    manifest_path = batch_dir / "batch-scan-manifest.yaml"
    plan_path = batch_dir / "program-batch-plan.md"
    delivery_root = Path(args.delivery_root).resolve() if args.delivery_root else None

    findings: list[str] = []
    warnings: list[str] = []

    if not status_path.is_file():
        findings.append(f"Missing status CSV: {status_path}")
        rows: list[dict[str, str]] = []
    else:
        rows = read_csv(status_path)

    if not manifest_path.is_file():
        findings.append(f"Missing batch manifest: {manifest_path}")
    elif args.require_terminal and manifest_top_level_value(manifest_path, "subagent_mode") == "prepare":
        if manifest_top_level_value(manifest_path, "scaffold_mode") != "precreate":
            findings.append(
                "Kiro/parallel batch requires scaffold_mode=precreate; "
                "reinitialize the batch before terminal validation."
            )
        expected_count, expected_count_finding = manifest_subagent_expected_count(manifest_path, rows)
        if expected_count_finding:
            findings.append(expected_count_finding)
        if (
            expected_count > 0
            and manifest_top_level_value(manifest_path, "status") != "subagent_results_merged"
        ):
            findings.append(
                "Kiro/parallel batch requires parent merge before terminal validation; "
                "run merge_subagent_results.py first."
            )
    manifest_locks = manifest_program_execution_locks(manifest_path)
    if not plan_path.is_file():
        findings.append(f"Missing program batch plan: {plan_path}")

    seen_members: dict[str, int] = {}
    output_dirs: dict[str, str] = {}
    for index, row in enumerate(rows, start=1):
        member = row.get("member", "")
        status = row.get("batch_status", "")
        validator_status = row.get("validator_status", "")
        output_dir_value = row.get("output_dir", "")
        expected_size_tier = row.get("size_tier", "").strip()
        if not member:
            findings.append(f"Row {index}: missing member")
        elif member in seen_members:
            warnings.append(f"Duplicate member {member!r} at rows {seen_members[member]} and {index}")
        else:
            seen_members[member] = index

        if status not in ALLOWED_STATUSES:
            findings.append(f"Row {index} {member}: invalid batch_status {status!r}")
        elif args.require_terminal and status in NON_TERMINAL_STATUSES:
            findings.append(
                f"Row {index} {member}: batch_status {status!r} is not terminal "
                "while --require-terminal is active"
            )

        if status == "in_progress" and not row.get("owner") and not row.get("session_id"):
            warnings.append(f"Row {index} {member}: in_progress without owner/session_id")

        if status in {"blocked_missing_source", "failed_validator", "failed_runtime"}:
            if not row.get("last_error"):
                findings.append(f"Row {index} {member}: {status} requires last_error")
            if not row.get("next_action"):
                findings.append(f"Row {index} {member}: {status} requires next_action")

        output_path = resolve_output_dir(output_dir_value, delivery_root)
        if output_dir_value and "<delivery-root>" not in output_dir_value:
            if output_dir_value in output_dirs and status not in {"skipped_not_program"}:
                findings.append(
                    f"Rows for {output_dirs[output_dir_value]} and {member} share output_dir {output_dir_value}"
                )
            output_dirs[output_dir_value] = member

        if status == "completed" and validator_status != "pass":
            findings.append(f"Row {index} {member}: completed requires validator_status pass")
        if status == "completed_with_warnings" and validator_status not in {"pass", "pass_with_warnings"}:
            findings.append(
                f"Row {index} {member}: completed_with_warnings requires validator_status pass/pass_with_warnings"
            )
        if status == "scanned_unvalidated" and validator_status != "deferred":
            findings.append(f"Row {index} {member}: scanned_unvalidated requires validator_status deferred")
        if status == "scanned_unvalidated" and not row.get("next_action"):
            findings.append(f"Row {index} {member}: scanned_unvalidated requires next_action for final validation")
        if status in ARTIFACT_REQUIRED_STATUSES:
            if output_path is None:
                message = (
                    f"Row {index} {member}: cannot verify placeholder/empty output_dir "
                    f"{output_dir_value!r}"
                )
                if args.require_terminal and status in {
                    "completed",
                    "completed_with_warnings",
                }:
                    findings.append(
                        message
                        + "; claimed terminal completion requires a concrete output_dir"
                    )
                else:
                    warnings.append(message)
                continue
            if not output_path.is_dir():
                findings.append(f"Row {index} {member}: output_dir does not exist: {output_path}")
                continue
            expected_artifacts = required_artifacts_for_member(member)
            missing = sorted(name for name in expected_artifacts if not (output_path / name).is_file())
            if missing:
                findings.append(f"Row {index} {member}: missing required artifacts: {', '.join(missing)}")
            for base_name in SCAFFOLD_TEXT_BASE_NAMES:
                artifact_name = required_artifact_for_member(member, base_name)
                artifact_path = output_path / artifact_name
                if not artifact_path.is_file():
                    continue
                text = artifact_path.read_text(encoding="utf-8-sig")
                matches = scaffold_patterns_in(text)
                if matches:
                    findings.append(
                        f"Row {index} {member}: {artifact_name} still appears to be a scaffold "
                        "or pending deep-read artifact; run semantic source deep-read and replace "
                        "placeholder content before marking completed. Matched: "
                        + ", ".join(matches)
                    )

            for artifact_path in retained_semantic_artifacts(output_path, member):
                matches = scaffold_patterns_in(
                    artifact_path.read_text(encoding="utf-8-sig"),
                    RETAINED_SEMANTIC_PATTERNS,
                )
                if not matches:
                    continue
                artifact_label = str(artifact_path.relative_to(output_path))
                findings.append(
                    f"Row {index} {member}: {artifact_label} still contains pending "
                    "semantic/indexer seed content; complete every retained deep-read "
                    "batch and update the routine YAML before marking the row complete. "
                    "Matched: "
                    + ", ".join(matches)
                )

            analysis_path = output_path / required_artifact_for_member(member, "program-analysis.md")
            if analysis_path.is_file():
                for finding in reader_first_layout_findings(
                    analysis_path.read_text(encoding="utf-8-sig")
                ):
                    findings.append(f"Row {index} {member}: {finding}")

            if (
                args.require_terminal
                and status in {"completed", "completed_with_warnings"}
                and not missing
            ):
                lock = manifest_locks.get(member.upper(), {})
                expected_source_index_sha256 = ""
                expected_execution_plan_sha256 = ""
                if expected_size_tier == "large_extreme_program":
                    expected_source_index_sha256 = lock.get("source_index_sha256", "")
                    expected_execution_plan_sha256 = lock.get(
                        "deep_read_execution_plan_sha256", ""
                    )
                    if not expected_source_index_sha256 or not expected_execution_plan_sha256:
                        findings.append(
                            f"Row {index} {member}: large-program terminal completion requires "
                            "a precreated immutable execution lock in batch-scan-manifest.yaml; "
                            "reinitialize with --scaffold-mode precreate."
                        )
                    row_source_lock = row.get("source_index_sha256", "").strip()
                    row_plan_lock = row.get("deep_read_execution_plan_sha256", "").strip()
                    if (
                        expected_source_index_sha256
                        and row_source_lock
                        and row_source_lock != expected_source_index_sha256
                    ) or (
                        expected_execution_plan_sha256
                        and row_plan_lock
                        and row_plan_lock != expected_execution_plan_sha256
                    ):
                        findings.append(
                            f"Row {index} {member}: status CSV execution lock does not match "
                            "the immutable batch manifest"
                        )
                for finding in upstream_contract_findings(
                    output_path,
                    expected_size_tier=expected_size_tier,
                    expected_source_index_sha256=expected_source_index_sha256,
                    expected_execution_plan_sha256=expected_execution_plan_sha256,
                ):
                    findings.append(
                        f"Row {index} {member}: upstream program-analysis contract failed: {finding}"
                    )

    for warning in warnings:
        print(f"WARNING: {warning}")
    if findings:
        for finding in findings:
            print(f"ERROR: {finding}")
        print(f"Batch status validation failed: {len(findings)} error(s), {len(warnings)} warning(s)")
        return 1
    print(f"Batch status validation passed: {len(rows)} row(s), {len(warnings)} warning(s)")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--batch-dir", required=True, help="Program batch directory")
    parser.add_argument("--status-list", help="Override path to program-list-status.csv")
    parser.add_argument("--delivery-root", help="Resolve relative output_dir values under this root")
    parser.add_argument(
        "--require-terminal",
        action="store_true",
        help="Fail when any row is still queued or in_progress",
    )
    return parser


if __name__ == "__main__":
    sys.exit(validate(build_parser().parse_args()))
