#!/usr/bin/env python3
"""Generate a human-readable STATUS.md from a project's workflow-state.yaml.

Reads `docs/<project>/workflow-state.yaml` and emits
`docs/<project>/STATUS.md` — a single-page project snapshot showing
current focus, all capabilities, open blockers, and recent activity.

Designed to be called by the orchestrator at Step 8.5 (after writing
state) so the human-readable status is always in sync with the machine
state.

Usage:
  python3 scripts/generate-status.py docs/<project-name>/
  python3 scripts/generate-status.py docs/<project-name>/workflow-state.yaml

Either accepts the project directory or the state file path itself.

Exit 0 on success, 1 on errors.

Standalone: only depends on PyYAML.
"""

from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML is required. Install with: pip install pyyaml")
    sys.exit(2)


def load_state(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


STAGE_TO_PROGRESS = [
    ("0", 0, "Evidence Intake"),
    ("1", 1, "Evidence Ready"),
    ("2", 2, "Inventory"),
    ("3a", 3, "Program Analysis"),
    ("3b", 3, "Program Analysis"),
    ("3c", 4, "Flow Analysis"),
    ("3d", 4, "Flow Analysis"),
    ("3e", 5, "Module Analysis"),
    ("3f", 5, "Module Analysis"),
    ("4a", 5, "Static Analysis (supplemental)"),
    ("4b", 5, "Static Analysis (supplemental)"),
    ("5", 5, "Runtime Evidence (supplemental)"),
    ("6", 5, "Business Rules"),
    ("7", 5, "Capabilities Mapped"),
    ("8a", 6, "Spec Drafted"),
    ("8b", 7, "Spec In Review"),
    ("8c", 8, "Spec Approved"),
    ("9", 9, "Equivalence Pack Ready"),
    ("10", 10, "Forward Handoff Ready"),
]


def stage_to_progress(stage_id: str | None) -> tuple[int, int, str]:
    """Map a stage_id to (current_step, total_steps, milestone_label)."""
    if not stage_id:
        return (0, 10, "not started")
    # Match longest prefix first (3a before 3, 8c before 8)
    s = stage_id.strip().lower()
    sorted_map = sorted(STAGE_TO_PROGRESS, key=lambda x: -len(x[0]))
    for prefix, step, label in sorted_map:
        if s.startswith(prefix.lower()):
            return (step, 10, label)
    return (0, 10, "unknown stage")


def progress_bar(current: int, total: int) -> str:
    filled = "●" * current  # ●
    empty = "○" * (total - current)  # ○
    return f"[{filled}{empty}] {current}/{total}"


def fmt_blocking(blocking: dict) -> str:
    if not isinstance(blocking, dict):
        return "—"
    parts: list[str] = []
    tbds = blocking.get("tbds") or []
    pending = blocking.get("sme_pending") or []
    gates = blocking.get("gates") or []
    if tbds:
        parts.append(f"{len(tbds)} TBD")
    if pending:
        parts.append(f"{len(pending)} SME pending")
    if gates:
        parts.append(f"gates: {', '.join(gates)}")
    return " · ".join(parts) if parts else "—"


def render(state: dict) -> str:
    project = state.get("project") or {}
    focus = state.get("current_focus") or {}
    caps = state.get("capabilities") or []
    history = state.get("history") or []

    active = [c for c in caps if not c.get("archived")]
    archived = [c for c in caps if c.get("archived")]

    lines: list[str] = []

    name = project.get("name") or "(unnamed)"
    lines.append(f"# Project Status: {name}")
    lines.append("")
    lines.append(
        f"> Auto-generated by `scripts/generate-status.py` from "
        f"`{project.get('root', 'docs/?')}workflow-state.yaml`."
    )
    lines.append(
        f"> Last updated: {project.get('last_updated_at', '?')} "
        f"by {project.get('last_updated_by', '?')}."
    )
    lines.append("> Do NOT edit by hand — your changes will be overwritten.")
    lines.append("")

    # Current Focus
    lines.append("## Current Focus")
    lines.append("")
    if not focus or not focus.get("capability_id"):
        lines.append("_No current focus. Run the orchestrator to set one._")
    else:
        stage_id = focus.get("stage_id", "?")
        step, total, label = stage_to_progress(stage_id)
        bar = progress_bar(step, total)
        gates = focus.get("open_gates") or []
        gate_str = ", ".join(gates) if gates else "(none)"
        lines.append(f"- **Progress:** `{bar}` — {label}")
        lines.append(f"- **Capability:** {focus.get('capability_id', '?')}")
        if focus.get("module_slug"):
            lines.append(f"- **Module:** {focus['module_slug']}")
        lines.append(f"- **Stage:** {stage_id}")
        lines.append(f"- **Next Skill:** {focus.get('next_skill', '?')}")
        lines.append(f"- **Next Artifact:** `{focus.get('next_artifact', '?')}`")
        lines.append(f"- **Open Gates:** {gate_str}")
        if focus.get("stage_card"):
            lines.append(f"- **Stage Card:** [`{focus['stage_card']}`]({focus['stage_card']})")
    lines.append("")

    # Capabilities
    lines.append(
        f"## Capabilities ({len(active)} in flight"
        + (f", {len(archived)} archived" if archived else "")
        + ")"
    )
    lines.append("")
    if not active:
        lines.append("_No capabilities tracked yet._")
    else:
        lines.append("| ID | Module | Progress | Stage | Last Updated | Blocking |")
        lines.append("| --- | --- | --- | --- | --- | --- |")
        for cap in active:
            cap_id = cap.get("id", "?")
            module = cap.get("module_slug") or "—"
            stage = cap.get("stage_id") or "?"
            step, total, _label = stage_to_progress(stage)
            bar = progress_bar(step, total)
            updated = cap.get("last_updated") or "?"
            blocking = fmt_blocking(cap.get("blocking") or {})
            lines.append(
                f"| {cap_id} | {module} | `{bar}` | {stage} | {updated} | {blocking} |"
            )
    lines.append("")

    if archived:
        lines.append(f"### Archived ({len(archived)})")
        lines.append("")
        for cap in archived:
            lines.append(
                f"- {cap.get('id', '?')} "
                f"(last stage: {cap.get('stage_id', '?')})"
            )
        lines.append("")

    # Open Blockers
    lines.append("## Open Blockers")
    lines.append("")
    any_blocker = False
    for cap in active:
        blocking = cap.get("blocking") or {}
        tbds = blocking.get("tbds") or []
        pending = blocking.get("sme_pending") or []
        gates = blocking.get("gates") or []
        if tbds or pending or gates:
            any_blocker = True
            lines.append(f"### {cap.get('id', '?')}")
            if tbds:
                lines.append(f"- **TBDs:** {', '.join(tbds)}")
            if pending:
                lines.append(f"- **SME pending:** {', '.join(pending)}")
            if gates:
                lines.append(f"- **Gates blocking:** {', '.join(gates)}")
            lines.append("")
    if not any_blocker:
        lines.append("_No open blockers._")
        lines.append("")

    # Recent Activity
    lines.append(f"## Recent Activity (last {min(10, len(history))})")
    lines.append("")
    if not history:
        lines.append("_No history yet._")
    else:
        recent = list(history[-10:])
        recent.reverse()
        lines.append("| When | Skill | Capability | Stage After | Note |")
        lines.append("| --- | --- | --- | --- | --- |")
        for entry in recent:
            at = entry.get("at") or "?"
            if isinstance(at, datetime):
                at = at.isoformat()
            skill = entry.get("skill") or "?"
            cap = entry.get("capability_id") or "—"
            stage = entry.get("stage_after") or "—"
            note = (entry.get("note") or "").replace("|", "\\|")[:80]
            lines.append(f"| {at} | {skill} | {cap} | {stage} | {note} |")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "Re-render with: `python3 scripts/generate-status.py "
        f"{project.get('root', 'docs/<project>/')}`"
    )
    lines.append("")

    return "\n".join(lines)


def resolve_paths(arg: str) -> tuple[Path, Path]:
    p = Path(arg)
    if p.is_dir():
        state_path = p / "workflow-state.yaml"
    elif p.name == "workflow-state.yaml":
        state_path = p
    else:
        state_path = p / "workflow-state.yaml"
    out_path = state_path.parent / "STATUS.md"
    return state_path, out_path


def main() -> int:
    if len(sys.argv) != 2:
        print("Usage: python3 scripts/generate-status.py <docs/<project>/ | path/to/workflow-state.yaml>")
        return 2
    state_path, out_path = resolve_paths(sys.argv[1])
    if not state_path.exists():
        print(f"ERROR: state file not found: {state_path}")
        return 1
    state = load_state(state_path)
    content = render(state)
    out_path.write_text(content, encoding="utf-8")
    print(f"OK: wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
