#!/usr/bin/env python3
"""Validate program-analyzer artifact contract completeness.

This checker is intentionally mechanical. It does not judge whether the
analysis is semantically correct; it catches compressed or partial wrapper
outputs that omit required sections, declared sidecars, or RLOG coverage.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any


REQUIRED_PROGRAM_SECTIONS = (
    "Program Reading Summary",
    "Calculation Logic",
    "Validation Logic",
    "Exception Handling",
    "Message Inventory",
    "Metadata",
    "Analysis Coverage & Scope",
    "Program Call Map",
    "Routine Cards",
    "Routine Logic Details",
    "Deep Read Windows",
    "Entry Points & Parameters",
    "Object Dependencies",
    "Logic Decomposition Ledger",
    "Data Touch Map",
    "Key File & Field Logic",
    "Control Flow",
    "File I/O",
    "External Calls",
    "Error Handling",
    "Redundancy Candidate Notes",
    "TBDs & Blocking Status",
    "Review Checklist",
)

CORE_SIDECAR_KEYS = (
    "source_index",
    "routine_index",
    "routine_logic_details",
    "routine_logic_details_yaml",
    "message_inventory_yaml",
)

ROUTINE_FINAL_SECTIONS = (
    "Calculation Logic",
    "Validation Logic",
    "Exception Handling",
    "Message Inventory",
    "Routine Detail Index",
    "Routine Details",
)

BATCH_CORE_SECTIONS = (
    "Calculation Logic",
    "Validation Logic",
    "Exception Handling",
)

CORE_SECTION_OVERVIEW_HEADINGS = {
    "Calculation Logic": ("Calculation Logic Overview",),
    "Validation Logic": ("Validation Logic Overview",),
    "Exception Handling": ("Exception Flow Overview", "Exception Handling Overview"),
}

BATCH_REQUIRED_SECTIONS = (
    "Calculation Logic",
    "Validation Logic",
    "Exception Handling",
    "Scope",
    "Batch Coverage Summary",
    "Message Inventory",
    "Routine Details",
)

RLOG_RE = re.compile(r"\bRLOG-[A-Z0-9_#$@-]+-\d{3}\b", re.I)
DEEP_READ_WINDOW_RE = re.compile(r"\bDRW-[A-Z0-9_#$@-]+-\d{3}\b", re.I)
FENCED_CODE_RE = re.compile(r"```")
FIXED_FORMAT_SOURCE_RE = re.compile(
    r"^\s*(?:[A-Z0-9_#$@]{1,10}\s+)?C\s{2,}.*\b"
    r"(EXSR|BEGSR|ENDSR|CHAIN|SETLL|READE|READP?E?|READ|WRITE|UPDATE|"
    r"DELETE|EXFMT|CALLP?|CALLPRC|EVAL|MOVE|MOVEL|Z-ADD|ADD|SUB|MULT|DIV|"
    r"MONITOR|ON-ERROR|MONMSG|SNDPGMMSG)\b",
    re.I,
)
FREE_FORMAT_SOURCE_RE = re.compile(
    r"^\s*(IF|WHEN|DOW|DOU|FOR|SELECT|MONITOR|ON-ERROR|RETURN|EVAL|"
    r"EXEC\s+SQL|CHAIN|SETLL|READE|READP?E?|READ|WRITE|UPDATE|DELETE|"
    r"CALLP?|EXSR|DCL-[A-Z]+)\b.+;\s*$",
    re.I,
)
SQL_SOURCE_RE = re.compile(
    r"^\s*(SELECT|UPDATE|INSERT|DELETE|MERGE)\s+.+\b(FROM|SET|INTO|WHERE)\b.*;?\s*$",
    re.I,
)
UNRESOLVED_MESSAGE_DESCRIPTION = "unresolved - message description not available"
UNRESOLVED_DESCRIPTION_SOURCES = {
    "",
    "unresolved",
    "missing_message_catalog_or_reference_pack",
    "missing_message_file",
    "pending_message_file",
}
UNRESOLVED_DESCRIPTION_STATUSES = {
    "unresolved",
    "unresolved_description",
    "pending_message_file",
}
STALE_DEEP_READ_GAP_PATTERNS = (
    re.compile(r"\bRemaining routine deep-read gaps\b", re.I),
    re.compile(r"\bnot-yet-deep-read routines\b", re.I),
    re.compile(r"\bnot deep-read routines?\b", re.I),
)
READER_FIRST_PLACEHOLDER_PATTERNS = (
    re.compile(r"\bpending reader-oriented summary\b", re.I),
    re.compile(r"\bpending semantic deep-read\b", re.I),
    re.compile(r"\bpending semantic detail\b", re.I),
    re.compile(r"\bplaceholder content\b", re.I),
    re.compile(r"\bplaceholder\b", re.I),
    re.compile(r"\bnot-yet-deep-read\b", re.I),
    re.compile(r"\bnot deep-read\b", re.I),
)
SEMANTIC_SEED_PATTERNS = (
    re.compile(r"\bBatch seed generated by\s+`?index_rpg_source\.py`?", re.I),
    re.compile(r"\bpending semantic deep-read\b", re.I),
    re.compile(r"\bpending semantic detail\b", re.I),
    re.compile(r"\bpending_deep_read\b", re.I),
    re.compile(r"\bsemantic(?:_|\s+)status\s*:\s*`?pending_deep_read`?\b", re.I),
    re.compile(r"\b(?:execution trigger|step-by-step logic)\s*:\s*pending deep read\b", re.I),
    re.compile(r"\bRLOG\s+pending\b", re.I),
)
PENDING_SEMANTIC_STATUSES = {"pending", "pending_deep_read", "indexed_only"}
DEEP_READ_COMPLETE_STATUS = "deep_read_complete"
BATCH_STRUCTURED_SEMANTIC_FIELDS = (
    "step_by_step_logic",
    "field_calculations",
    "conditioned_calculation_blocks",
    "outcome_reverse_traces",
    "field_lineage",
    "branch_outcomes",
    "routine_exception_closure",
)
MEANINGFUL_WORD_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9_#$@/-]*|[\u4e00-\u9fff]{2,}")
ARTIFACT_SAFE_RE = re.compile(r'[\s<>:"/\\|?*]+')


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def load_yaml(path: Path) -> Any:
    try:
        import yaml  # type: ignore
    except ImportError as exc:  # pragma: no cover - depends on local runtime
        raise RuntimeError(
            "PyYAML is required to validate YAML sidecar declarations. "
            "Install with: pip install pyyaml"
        ) from exc
    with path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def artifact_program_prefix(program_name: str) -> str:
    prefix = ARTIFACT_SAFE_RE.sub("_", program_name.strip().upper())
    prefix = prefix.strip("._-")
    return prefix or "PROGRAM"


def find_artifact_path(analysis_dir: Path, base_name: str) -> Path | None:
    prefixed_matches = sorted(analysis_dir.glob(f"*-{base_name}"))
    if len(prefixed_matches) == 1:
        return prefixed_matches[0]
    generic_path = analysis_dir / base_name
    if generic_path.is_file():
        return generic_path
    return None


def find_program_analysis_path(analysis_dir: Path, explicit_path: Path | None) -> Path | None:
    if explicit_path is not None:
        return explicit_path
    prefixed_matches = sorted(analysis_dir.glob("*-program-analysis.md"))
    if len(prefixed_matches) == 1:
        return prefixed_matches[0]
    default_path = analysis_dir / "program-analysis.md"
    if default_path.is_file():
        return default_path
    matches = sorted(analysis_dir.glob("program-analysis-*.md"))
    if len(matches) == 1:
        return matches[0]
    return None


def summary_path(analysis_dir: Path) -> Path | None:
    return find_artifact_path(analysis_dir, "program-analysis-summary.yaml")


def sidecar_entries_for_dir(analysis_dir: Path) -> dict[str, dict[str, str]]:
    path = summary_path(analysis_dir)
    if path is None or not path.is_file():
        return {}
    payload = load_yaml(path)
    sidecars = (payload or {}).get("sidecars", {})
    if not isinstance(sidecars, dict):
        return {}
    entries: dict[str, dict[str, str]] = {}
    for key, value in sidecars.items():
        if not isinstance(value, dict):
            continue
        entries[str(key)] = {
            "path": str(value.get("path", "")),
            "status": str(value.get("status", "")),
        }
    return entries


def declared_sidecar_path(
    analysis_dir: Path,
    sidecar_key: str,
    fallback_base_name: str,
) -> Path | None:
    entry = sidecar_entries_for_dir(analysis_dir).get(sidecar_key)
    if entry:
        rel_path = entry.get("path", "")
        if rel_path:
            candidate = analysis_dir / rel_path
            if candidate.is_file():
                return candidate
    return find_artifact_path(analysis_dir, fallback_base_name)


def h2_positions(markdown: str) -> dict[str, int]:
    positions: dict[str, int] = {}
    for match in re.finditer(r"^##\s+(.+?)\s*$", markdown, re.M):
        heading = match.group(1).strip()
        positions.setdefault(heading, match.start())
    return positions


def heading_positions(markdown: str) -> dict[str, int]:
    positions: dict[str, int] = {}
    for match in re.finditer(r"^#{2,6}\s+(.+?)\s*$", markdown, re.M):
        heading = match.group(1).strip()
        positions.setdefault(heading, match.start())
    return positions


def heading_spans(markdown: str) -> dict[str, tuple[int, int]]:
    matches = list(re.finditer(r"^(#{2,6})\s+(.+?)\s*$", markdown, re.M))
    spans: dict[str, tuple[int, int]] = {}
    for index, match in enumerate(matches):
        heading = match.group(2).strip()
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(markdown)
        spans.setdefault(heading, (start, end))
    return spans


def h2_section_text(markdown: str, heading: str) -> str:
    pattern = re.compile(r"^##\s+(.+?)\s*$", re.M)
    matches = list(pattern.finditer(markdown))
    for index, match in enumerate(matches):
        if match.group(1).strip() != heading:
            continue
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(markdown)
        return markdown[start:end]
    return ""


def h3_blocks(section_text: str) -> list[tuple[str, int, str]]:
    matches = list(re.finditer(r"^###\s+(.+?)\s*$", section_text, re.M))
    blocks: list[tuple[str, int, str]] = []
    for index, match in enumerate(matches):
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(section_text)
        blocks.append((match.group(1).strip(), match.start(), section_text[start:end]))
    return blocks


def validate_ordered_headings(
    markdown: str,
    required_headings: tuple[str, ...],
    artifact_label: str,
) -> list[str]:
    findings: list[str] = []
    positions = heading_positions(markdown)
    missing = [heading for heading in required_headings if heading not in positions]
    if missing:
        findings.append(f"{artifact_label} missing required headings: " + ", ".join(missing))
        return findings
    ordered_positions = [positions[heading] for heading in required_headings]
    if ordered_positions != sorted(ordered_positions):
        findings.append(f"{artifact_label} required headings are out of order")
    return findings


def validate_ordered_h2_headings(
    markdown: str,
    required_headings: tuple[str, ...],
    artifact_label: str,
) -> list[str]:
    findings: list[str] = []
    positions = h2_positions(markdown)
    missing = [heading for heading in required_headings if heading not in positions]
    if missing:
        findings.append(f"{artifact_label} missing required ## headings: " + ", ".join(missing))
        return findings
    ordered_positions = [positions[heading] for heading in required_headings]
    if ordered_positions != sorted(ordered_positions):
        findings.append(f"{artifact_label} required ## headings are out of order")
    return findings


def table_cells_or_line(line: str) -> list[str]:
    stripped = line.strip()
    if not stripped:
        return []
    if stripped.startswith("|") and stripped.endswith("|"):
        cells = [cell.strip() for cell in stripped.strip("|").split("|")]
        return [
            cell
            for cell in cells
            if cell and not re.fullmatch(r":?-{3,}:?", cell)
        ]
    return [stripped]


def has_reader_first_placeholder(text: str) -> bool:
    return any(pattern.search(text) for pattern in READER_FIRST_PLACEHOLDER_PATTERNS)


def semantic_seed_matches(text: str) -> list[str]:
    return [
        pattern.pattern.replace("\\b", "")
        for pattern in SEMANTIC_SEED_PATTERNS
        if pattern.search(text)
    ]


def meaningful_word_count(text: str) -> int:
    cleaned = re.sub(r"`[^`]*`", " ", text)
    cleaned = RLOG_RE.sub(" ", cleaned)
    cleaned = re.sub(r"\bSR\d{3,}\b", " ", cleaned, flags=re.I)
    return len(MEANINGFUL_WORD_RE.findall(cleaned))


def is_markdown_separator_row(cells: list[str]) -> bool:
    return bool(cells) and all(re.fullmatch(r":?-{3,}:?", cell.strip()) for cell in cells)


def markdown_table_rows(section_text: str) -> list[list[str]]:
    rows: list[list[str]] = []
    for line in section_text.splitlines():
        stripped = line.strip()
        if not stripped.startswith("|") or not stripped.endswith("|"):
            continue
        cells = [cell.strip() for cell in stripped.strip("|").split("|")]
        if is_markdown_separator_row(cells):
            continue
        rows.append(cells)
    return rows


def has_exact_pending_cell(cell: str) -> bool:
    normalized = re.sub(r"[*_`]", "", cell).strip().lower()
    return normalized == "pending"


def strip_inline_code_marks(text: str) -> str:
    return text.replace("`", "").strip()


def looks_like_source_snippet(text: str) -> bool:
    candidate = strip_inline_code_marks(text)
    if not candidate:
        return False
    if FIXED_FORMAT_SOURCE_RE.search(candidate):
        return True
    if FREE_FORMAT_SOURCE_RE.search(candidate):
        return True
    if SQL_SOURCE_RE.search(candidate):
        return True
    return False


def validate_batch_core_has_no_source_snippets(
    batch_text: str,
    batch_label: str,
) -> list[str]:
    findings: list[str] = []
    spans = heading_spans(batch_text)
    for section in BATCH_CORE_SECTIONS:
        span = spans.get(section)
        if span is None:
            continue
        section_text = batch_text[span[0] : span[1]]
        if FENCED_CODE_RE.search(section_text):
            findings.append(
                f"{batch_label} {section} core logic must not contain fenced source/code blocks"
            )
        for line_number, line in enumerate(section_text.splitlines(), start=1):
            for cell in table_cells_or_line(line):
                if looks_like_source_snippet(cell):
                    findings.append(
                        f"{batch_label} {section} core logic contains a source-code-like snippet "
                        f"near section line {line_number}: {cell[:80]}"
                    )
                    break
    return findings


def validate_batch_core_has_no_pending_cells(
    batch_text: str,
    batch_label: str,
) -> list[str]:
    findings: list[str] = []
    spans = heading_spans(batch_text)
    for section in BATCH_CORE_SECTIONS:
        span = spans.get(section)
        if span is None:
            continue
        rows = markdown_table_rows(batch_text[span[0] : span[1]])
        for row_number, row in enumerate(rows[1:], start=1):
            pending_columns = [
                str(column_number)
                for column_number, cell in enumerate(row, start=1)
                if has_exact_pending_cell(cell)
            ]
            if pending_columns:
                findings.append(
                    f"{batch_label} {section} contains an unresolved pending table cell "
                    f"in data row {row_number}, column(s) {', '.join(pending_columns)}"
                )
    return findings


def extract_rlog_detail_blocks(markdown: str) -> dict[str, str]:
    matches = list(
        re.finditer(
            r"^#{2,6}\s+(RLOG-[A-Z0-9_#$@-]+-\d{3})\b.*$",
            markdown,
            re.I | re.M,
        )
    )
    blocks: dict[str, str] = {}
    for index, match in enumerate(matches):
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(markdown)
        blocks[match.group(1).upper()] = markdown[start:end]
    return blocks


def validate_rlog_block_quality(
    markdown: str,
    expected_ids: list[str] | None,
    artifact_label: str,
) -> list[str]:
    findings: list[str] = []
    blocks = extract_rlog_detail_blocks(markdown)
    if expected_ids is None and not blocks:
        return [f"{artifact_label} Routine Details has no RLOG semantic detail blocks"]
    ids_to_check = expected_ids if expected_ids is not None else list(blocks)
    for rlog_id in ids_to_check:
        body = blocks.get(rlog_id, "")
        if not body:
            findings.append(
                f"{artifact_label} missing reader-useful detail heading/body for {rlog_id}"
            )
        elif semantic_seed_matches(body) or meaningful_word_count(body) < 12:
            findings.append(
                f"{artifact_label} {rlog_id} needs reader-useful source-backed semantic detail"
            )
    return findings


def validate_required_sections(program_markdown: str) -> list[str]:
    findings: list[str] = []
    positions = h2_positions(program_markdown)
    missing = [section for section in REQUIRED_PROGRAM_SECTIONS if section not in positions]
    if missing:
        findings.append("program-analysis.md missing required sections: " + ", ".join(missing))
        return findings

    ordered_positions = [positions[section] for section in REQUIRED_PROGRAM_SECTIONS]
    if ordered_positions != sorted(ordered_positions):
        findings.append(
            "program-analysis.md required sections are out of order; follow "
            "references/output-contract.md File Structure"
        )
    return findings


def extract_rlog_ids_from_yaml(path: Path) -> list[str]:
    payload = load_yaml(path)
    inventory = (payload or {}).get("routine_logic_inventory", {})
    details = inventory.get("details", []) if isinstance(inventory, dict) else []
    ids: list[str] = []
    for detail in details:
        if isinstance(detail, dict) and detail.get("detail_id"):
            ids.append(str(detail["detail_id"]).upper())
    return ids


def extract_rlog_ids_from_markdown(path: Path) -> list[str]:
    return [match.group(0).upper() for match in RLOG_RE.finditer(read_text(path))]


def extract_main_rlog_detail_headings(program_markdown: str) -> list[str]:
    section_text = h2_section_text(program_markdown, "Routine Logic Details")
    return [
        match.group(1).upper()
        for match in re.finditer(r"^###\s+(RLOG-[A-Z0-9_#$@-]+-\d{3})\b", section_text, re.I | re.M)
    ]


def rlog_suffix_number(rlog_id: str) -> int | None:
    match = re.search(r"-(\d{3})$", rlog_id)
    if match is None:
        return None
    return int(match.group(1))


def validate_rlog_sequence(label: str, rlog_ids: list[str]) -> list[str]:
    findings: list[str] = []
    if not rlog_ids:
        return findings
    numbers = [rlog_suffix_number(rlog_id) for rlog_id in rlog_ids]
    if any(number is None for number in numbers):
        findings.append(f"{label} contains malformed RLOG IDs")
        return findings
    normalized_numbers = [number for number in numbers if number is not None]
    expected = list(range(1, len(normalized_numbers) + 1))
    if normalized_numbers != expected:
        findings.append(
            f"{label} RLOG IDs must be continuous and ordered from 001; found "
            + ", ".join(rlog_ids)
        )
    return findings


def validate_rlog_coverage(analysis_dir: Path) -> list[str]:
    findings: list[str] = []
    yaml_path = declared_sidecar_path(
        analysis_dir,
        "routine_logic_details_yaml",
        "routine-logic-details.yaml",
    )
    markdown_path = declared_sidecar_path(
        analysis_dir,
        "routine_logic_details",
        "routine-logic-details.md",
    )
    if yaml_path is None or markdown_path is None or not yaml_path.is_file() or not markdown_path.is_file():
        return findings

    yaml_ids = extract_rlog_ids_from_yaml(yaml_path)
    markdown_ids = extract_rlog_ids_from_markdown(markdown_path)
    if not yaml_ids:
        findings.append("routine-logic-details.yaml has no routine_logic_inventory.details[].detail_id values")
        return findings

    findings.extend(validate_rlog_sequence("routine-logic-details.yaml", yaml_ids))

    missing = sorted(set(yaml_ids) - set(markdown_ids))
    if missing:
        findings.append(
            "routine-logic-details.md missing RLOG IDs declared in YAML: "
            + ", ".join(missing)
        )

    return findings


def validate_routine_yaml_semantic_completion(analysis_dir: Path) -> list[str]:
    yaml_path = declared_sidecar_path(
        analysis_dir,
        "routine_logic_details_yaml",
        "routine-logic-details.yaml",
    )
    if yaml_path is None or not yaml_path.is_file():
        return []

    payload = load_yaml(yaml_path)
    inventory = (payload or {}).get("routine_logic_inventory", {})
    if not isinstance(inventory, dict):
        return []

    pending_refs: list[str] = []
    for collection_name in ("summary", "details"):
        entries = inventory.get(collection_name, [])
        if not isinstance(entries, list):
            continue
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            semantic_status = str(entry.get("semantic_status") or "").strip().lower()
            seed_text = " ".join(
                str(entry.get(key) or "")
                for key in ("execution_trigger", "unresolved_routine_logic")
            )
            if (
                semantic_status in PENDING_SEMANTIC_STATUSES
                or re.search(r"\bpending deep read\b", seed_text, re.I)
            ):
                reference = str(
                    entry.get("detail_id")
                    or entry.get("detail_ref")
                    or entry.get("routine")
                    or "unknown routine"
                )
                pending_refs.append(reference)

    if not pending_refs:
        return []

    unique_refs = list(dict.fromkeys(pending_refs))
    preview = ", ".join(unique_refs[:12])
    if len(unique_refs) > 12:
        preview += f", ... (+{len(unique_refs) - 12} more)"
    return [
        f"{yaml_path.name} retains pending_deep_read semantic seed values "
        f"for: {preview}. Complete source deep-read and replace the seed fields before validation."
    ]


def validate_consolidated_routine_semantic_completion(analysis_dir: Path) -> list[str]:
    markdown_path = declared_sidecar_path(
        analysis_dir,
        "routine_logic_details",
        "routine-logic-details.md",
    )
    if markdown_path is None or not markdown_path.is_file():
        return []
    markdown = read_text(markdown_path)
    matches = semantic_seed_matches(markdown)
    findings: list[str] = []
    if matches:
        findings.append(
            f"{markdown_path.name} still contains pending semantic deep-read content; "
            "replace the indexer seed with source-backed routine detail. Matched: "
            + ", ".join(matches)
        )
    yaml_path = declared_sidecar_path(
        analysis_dir,
        "routine_logic_details_yaml",
        "routine-logic-details.yaml",
    )
    expected_ids = (
        extract_rlog_ids_from_yaml(yaml_path)
        if yaml_path is not None and yaml_path.is_file()
        else None
    )
    routine_detail_section = h2_section_text(markdown, "Routine Details") or markdown
    findings.extend(
        validate_rlog_block_quality(
            routine_detail_section,
            expected_ids,
            markdown_path.name,
        )
    )
    return findings


def validate_program_rlog_coverage(program_markdown: str, analysis_dir: Path) -> list[str]:
    yaml_path = declared_sidecar_path(
        analysis_dir,
        "routine_logic_details_yaml",
        "routine-logic-details.yaml",
    )
    if yaml_path is None or not yaml_path.is_file():
        return []

    yaml_ids = extract_rlog_ids_from_yaml(yaml_path)
    if not yaml_ids:
        return []

    findings: list[str] = []
    detail_heading_ids = extract_main_rlog_detail_headings(program_markdown)
    if not detail_heading_ids:
        findings.append(
            "program-analysis.md Routine Logic Details missing RLOG detail headings declared in YAML: "
            + ", ".join(yaml_ids)
        )
        return findings

    missing = sorted(set(yaml_ids) - set(detail_heading_ids))
    extra = sorted(set(detail_heading_ids) - set(yaml_ids))
    if missing:
        findings.append(
            "program-analysis.md Routine Logic Details missing RLOG detail headings declared in YAML: "
            + ", ".join(missing)
        )
    if extra:
        findings.append(
            "program-analysis.md Routine Logic Details contains extra RLOG detail headings not declared in YAML: "
            + ", ".join(extra)
        )
    if detail_heading_ids != yaml_ids:
        findings.append(
            "program-analysis.md Routine Logic Details RLOG headings must match YAML order and count"
        )
    findings.extend(validate_rlog_sequence("program-analysis.md Routine Logic Details", detail_heading_ids))
    return findings


def validate_core_logic_routine_indexes(program_markdown: str, analysis_dir: Path) -> list[str]:
    yaml_path = declared_sidecar_path(
        analysis_dir,
        "routine_logic_details_yaml",
        "routine-logic-details.yaml",
    )
    if yaml_path is None or not yaml_path.is_file():
        return []

    yaml_ids = extract_rlog_ids_from_yaml(yaml_path)
    if not yaml_ids:
        return []

    findings: list[str] = []
    for section in BATCH_CORE_SECTIONS:
        section_text = h2_section_text(program_markdown, section)
        index_heading = f"Routine Index For {section}"
        if index_heading not in section_text:
            findings.append(f"program-analysis.md missing {index_heading}")
            continue
        index_ids = [match.group(0).upper() for match in RLOG_RE.finditer(section_text)]
        missing = sorted(set(yaml_ids) - set(index_ids))
        if missing:
            findings.append(
                f"program-analysis.md {index_heading} missing RLOG rows declared in YAML: "
                + ", ".join(missing)
            )
        if len(index_ids) < len(yaml_ids):
            findings.append(
                f"program-analysis.md {index_heading} row count is {len(index_ids)}; "
                f"expected at least {len(yaml_ids)}"
            )
    return findings


def validate_program_reading_summary_quality(program_markdown: str) -> list[str]:
    section_text = h2_section_text(program_markdown, "Program Reading Summary")
    if not section_text:
        return []

    findings: list[str] = []
    if has_reader_first_placeholder(section_text) or meaningful_word_count(section_text) < 20:
        findings.append(
            "reader-first golden gate: Program Reading Summary must contain "
            "reader-oriented processing context, not placeholder or pending text"
        )

    required_headers = ("Processing Layer", "Main Routines", "What To Understand First")
    missing_headers = [header for header in required_headers if header not in section_text]
    if missing_headers:
        findings.append(
            "reader-first golden gate: Program Reading Summary missing processing-layer "
            "table headers: "
            + ", ".join(missing_headers)
        )
        return findings

    rows = markdown_table_rows(section_text)
    data_rows = [
        cells
        for cells in rows
        if cells
        and cells[0] != "Processing Layer"
        and len(cells) >= 3
        and not has_reader_first_placeholder(" ".join(cells))
        and meaningful_word_count(cells[2]) >= 5
    ]
    if not data_rows:
        findings.append(
            "reader-first golden gate: Program Reading Summary needs at least one "
            "processing-layer row with reader-useful explanation"
        )
    return findings


def validate_core_logic_reader_first_quality(
    program_markdown: str,
    analysis_dir: Path,
) -> list[str]:
    yaml_path = declared_sidecar_path(
        analysis_dir,
        "routine_logic_details_yaml",
        "routine-logic-details.yaml",
    )
    if yaml_path is None or not yaml_path.is_file():
        return []

    yaml_ids = extract_rlog_ids_from_yaml(yaml_path)
    if not yaml_ids:
        return []

    findings: list[str] = []
    for section in BATCH_CORE_SECTIONS:
        section_text = h2_section_text(program_markdown, section)
        if not section_text:
            continue

        index_heading = f"Routine Index For {section}"
        overview_text = section_text.split(index_heading, 1)[0]
        if has_reader_first_placeholder(overview_text) or meaningful_word_count(overview_text) < 4:
            findings.append(
                f"reader-first golden gate: program-analysis.md {section} must start "
                "with reader-oriented overview content before the routine index"
            )

        if index_heading not in section_text:
            continue
        index_text = section_text.split(index_heading, 1)[1]
        for rlog_id in yaml_ids:
            row = next(
                (line for line in index_text.splitlines() if rlog_id in line.upper()),
                "",
            )
            if not row:
                continue
            cells = table_cells_or_line(row)
            detail = cells[-1] if len(cells) >= 3 else row
            if has_reader_first_placeholder(detail) or meaningful_word_count(detail) < 3:
                findings.append(
                    f"reader-first golden gate: program-analysis.md {index_heading} "
                    f"{rlog_id} needs reader-useful detail, not pending/placeholder text"
                )
    return findings


def validate_core_logic_theme_sections(program_markdown: str) -> list[str]:
    findings: list[str] = []
    for section in BATCH_CORE_SECTIONS:
        section_text = h2_section_text(program_markdown, section)
        if not section_text:
            continue

        blocks = h3_blocks(section_text)
        overview_aliases = CORE_SECTION_OVERVIEW_HEADINGS[section]
        overview_block = next(
            (block for block in blocks if block[0] in overview_aliases),
            None,
        )
        if overview_block is None:
            findings.append(
                f"reader-first golden gate: program-analysis.md {section} "
                "missing themed overview heading: "
                + " or ".join(overview_aliases)
            )
        elif (
            has_reader_first_placeholder(overview_block[2])
            or meaningful_word_count(overview_block[2]) < 8
        ):
            findings.append(
                f"reader-first golden gate: program-analysis.md {overview_block[0]} "
                "needs reader-useful theme overview content"
            )

        index_heading = f"Routine Index For {section}"
        index_position = next(
            (position for heading, position, _body in blocks if heading == index_heading),
            len(section_text),
        )
        theme_blocks = [
            block
            for block in blocks
            if block[1] < index_position
            and block[0] != index_heading
            and block[0] not in overview_aliases
        ]
        if not theme_blocks:
            findings.append(
                f"reader-first golden gate: program-analysis.md {section} needs at least "
                "one reader-first theme subsection before the routine index"
            )
            continue

        for heading, _position, body in theme_blocks:
            if has_reader_first_placeholder(body) or meaningful_word_count(body) < 8:
                findings.append(
                    f"reader-first golden gate: program-analysis.md {section} theme "
                    f"subsection {heading} needs reader-useful detail"
                )
    return findings


def extract_main_rlog_detail_blocks(program_markdown: str) -> dict[str, str]:
    section_text = h2_section_text(program_markdown, "Routine Logic Details")
    matches = list(
        re.finditer(
            r"^###\s+(RLOG-[A-Z0-9_#$@-]+-\d{3})\b.*$",
            section_text,
            re.I | re.M,
        )
    )
    blocks: dict[str, str] = {}
    for index, match in enumerate(matches):
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(section_text)
        blocks[match.group(1).upper()] = section_text[start:end]
    return blocks


def validate_main_rlog_detail_quality(
    program_markdown: str,
    analysis_dir: Path,
) -> list[str]:
    yaml_path = declared_sidecar_path(
        analysis_dir,
        "routine_logic_details_yaml",
        "routine-logic-details.yaml",
    )
    if yaml_path is None or not yaml_path.is_file():
        return []

    yaml_ids = extract_rlog_ids_from_yaml(yaml_path)
    if not yaml_ids:
        return []

    findings: list[str] = []
    blocks = extract_main_rlog_detail_blocks(program_markdown)
    for rlog_id in yaml_ids:
        body = blocks.get(rlog_id, "")
        if not body:
            continue
        if has_reader_first_placeholder(body) or meaningful_word_count(body) < 12:
            findings.append(
                "reader-first golden gate: program-analysis.md Routine Logic Details "
                f"{rlog_id} needs reader-useful detail, not pending/placeholder text"
            )
    return findings


def validate_reader_first_golden_gate(program_markdown: str, analysis_dir: Path) -> list[str]:
    findings: list[str] = []
    findings.extend(validate_program_reading_summary_quality(program_markdown))
    findings.extend(validate_core_logic_reader_first_quality(program_markdown, analysis_dir))
    findings.extend(validate_core_logic_theme_sections(program_markdown))
    findings.extend(validate_main_rlog_detail_quality(program_markdown, analysis_dir))
    return findings


def validate_no_stale_gap_wording(program_markdown: str) -> list[str]:
    findings: list[str] = []
    for pattern in STALE_DEEP_READ_GAP_PATTERNS:
        if pattern.search(program_markdown):
            findings.append(
                "program-analysis.md contains stale deep-read gap wording: "
                + pattern.pattern.replace("\\b", "")
            )
    return findings


def batch_detail_files(analysis_dir: Path) -> list[Path]:
    declared = [
        analysis_dir / entry["path"]
        for key, entry in sidecar_entries_for_dir(analysis_dir).items()
        if key.startswith("routine_logic_deep_read_batch_")
        and entry.get("path")
        and (analysis_dir / entry["path"]).is_file()
    ]
    batch_dir = analysis_dir / "routine-logic-details"
    patterns = ("part-*.md", "*-part-*.md", "deep-read-batch-*.md", "*-deep-read-batch-*.md", "deep-batch-*.md", "*-deep-batch-*.md")
    files: list[Path] = list(declared)
    if batch_dir.is_dir():
        for pattern in patterns:
            files.extend(batch_dir.glob(pattern))
    return sorted(
        set(files),
        key=lambda path: tuple(
            (0, int(part)) if part.isdigit() else (1, part.lower())
            for part in re.split(r"(\d+)", path.as_posix())
        ),
    )


def semantic_value_is_complete(value: Any, minimum_words: int = 2) -> bool:
    if value is None or value == "" or value == [] or value == {}:
        return False
    text = str(value)
    return not semantic_seed_matches(text) and meaningful_word_count(text) >= minimum_words


def batch_coverage_column_ids(
    batch_text: str,
    accepted_headers: set[str],
    id_pattern: re.Pattern[str],
) -> list[str]:
    rows = markdown_table_rows(h2_section_text(batch_text, "Batch Coverage Summary"))
    if not rows:
        return []
    headers = [strip_inline_code_marks(cell).strip("*_ ").lower() for cell in rows[0]]
    column = next(
        (index for index, header in enumerate(headers) if header in accepted_headers),
        None,
    )
    if column is None:
        return []
    identifiers: list[str] = []
    for row in rows[1:]:
        if column >= len(row):
            continue
        identifiers.extend(match.group(0).upper() for match in id_pattern.finditer(row[column]))
    return list(dict.fromkeys(identifiers))


def batch_assigned_rlog_ids(batch_path: Path) -> list[str]:
    batch_text = read_text(batch_path)
    coverage_ids = batch_coverage_column_ids(
        batch_text,
        {"rlog detail", "rlog", "detail link"},
        RLOG_RE,
    )
    routine_section = h2_section_text(batch_text, "Routine Details")
    detail_ids = list(extract_rlog_detail_blocks(routine_section))
    return list(dict.fromkeys([*coverage_ids, *detail_ids]))


def batch_assigned_window_ids(batch_text: str) -> list[str]:
    return batch_coverage_column_ids(
        batch_text,
        {"window id", "deep-read window", "deep read window"},
        DEEP_READ_WINDOW_RE,
    )


def validate_batch_yaml_semantic_completion(analysis_dir: Path) -> list[str]:
    batches = batch_detail_files(analysis_dir)
    if not batches:
        return []
    yaml_path = declared_sidecar_path(
        analysis_dir,
        "routine_logic_details_yaml",
        "routine-logic-details.yaml",
    )
    if yaml_path is None or not yaml_path.is_file():
        return []

    payload = load_yaml(yaml_path)
    inventory = (payload or {}).get("routine_logic_inventory", {})
    if not isinstance(inventory, dict):
        return []
    detail_entries = inventory.get("details", [])
    summary_entries = inventory.get("summary", [])
    details_by_id = {
        str(entry.get("detail_id") or "").upper(): entry
        for entry in detail_entries
        if isinstance(entry, dict) and entry.get("detail_id")
    } if isinstance(detail_entries, list) else {}
    summary_by_id = {
        str(entry.get("detail_ref") or "").upper(): entry
        for entry in summary_entries
        if isinstance(entry, dict) and entry.get("detail_ref")
    } if isinstance(summary_entries, list) else {}

    assigned_ids: list[str] = []
    for batch_path in batches:
        assigned_ids.extend(batch_assigned_rlog_ids(batch_path))

    findings: list[str] = []
    for rlog_id in dict.fromkeys(assigned_ids):
        detail = details_by_id.get(rlog_id)
        if detail is None:
            findings.append(
                f"{yaml_path.name} missing details[] semantic record for batched {rlog_id}"
            )
            continue
        semantic_status = str(detail.get("semantic_status") or "").strip().lower()
        coverage = str(detail.get("coverage") or "").strip().lower()
        if semantic_status != DEEP_READ_COMPLETE_STATUS:
            findings.append(
                f"{yaml_path.name} batched {rlog_id} requires "
                f"semantic_status: {DEEP_READ_COMPLETE_STATUS}, found {semantic_status or 'missing'}"
            )
        if coverage != "deep_read":
            findings.append(
                f"{yaml_path.name} batched {rlog_id} requires coverage: deep_read, "
                f"found {coverage or 'missing'}"
            )
        if not semantic_value_is_complete(detail.get("execution_trigger"), minimum_words=3):
            findings.append(
                f"{yaml_path.name} batched {rlog_id} needs a source-backed execution_trigger"
            )
        incomplete_fields = [
            field
            for field in BATCH_STRUCTURED_SEMANTIC_FIELDS
            if not semantic_value_is_complete(detail.get(field))
        ]
        if incomplete_fields:
            findings.append(
                f"{yaml_path.name} batched {rlog_id} has incomplete structured semantic "
                "field(s): " + ", ".join(incomplete_fields)
            )

        summary = summary_by_id.get(rlog_id)
        if summary is None:
            findings.append(
                f"{yaml_path.name} missing summary[] mirror for batched {rlog_id}"
            )
            continue
        summary_status = str(summary.get("semantic_status") or "").strip().lower()
        summary_coverage = str(summary.get("coverage") or "").strip().lower()
        if summary_status != semantic_status or summary_coverage != coverage:
            findings.append(
                f"{yaml_path.name} summary[] and details[] semantic state disagree for "
                f"batched {rlog_id}"
            )
    return findings


def summary_payload(analysis_dir: Path) -> dict[str, Any]:
    path = summary_path(analysis_dir)
    if path is None or not path.is_file():
        return {}
    payload = load_yaml(path)
    return payload if isinstance(payload, dict) else {}


def requires_large_program_batches(payload: dict[str, Any]) -> bool:
    if payload.get("program_size_tier") == "large_extreme_program":
        return True
    counts = payload.get("counts", {})
    if isinstance(counts, dict) and int(counts.get("source_lines", 0) or 0) > 10000:
        return True
    source = payload.get("source", {})
    if isinstance(source, dict) and int(source.get("line_count", 0) or 0) > 10000:
        return True
    return False


def validate_large_program_batches(analysis_dir: Path) -> list[str]:
    payload = summary_payload(analysis_dir)
    if not payload or not requires_large_program_batches(payload):
        return []

    findings: list[str] = []
    batches = batch_detail_files(analysis_dir)
    if not batches:
        findings.append(
            "large_extreme_program requires routine-logic-details/deep-read-batch-*.md "
            "batch checkpoint files"
        )
        return findings

    program = str(payload.get("program") or "").strip()
    batch_dir = analysis_dir / "routine-logic-details"
    prefix = artifact_program_prefix(program) if program else ""
    canonical_first = batch_dir / f"{prefix}-deep-read-batch-001.md" if prefix else None
    alias_first = batch_dir / f"{prefix}-deep-batch-001.md" if prefix else None
    legacy_first = analysis_dir / "routine-logic-details" / "deep-read-batch-001.md"
    wildcard_first = sorted(batch_dir.glob("*-deep-read-batch-001.md")) if not prefix else []
    canonical_ok = canonical_first is not None and canonical_first.is_file()
    alias_ok = alias_first is not None and alias_first.is_file()
    if not canonical_ok and not alias_ok and not wildcard_first:
        if legacy_first.is_file():
            return findings
        findings.append(
            "large_extreme_program requires a first batch checkpoint: "
            "routine-logic-details/<PROGRAM>-deep-read-batch-001.md"
        )
    return findings


def validate_routine_detail_review_surfaces(analysis_dir: Path) -> list[str]:
    findings: list[str] = []
    batches = batch_detail_files(analysis_dir)
    if not batches:
        return findings

    routine_markdown_path = declared_sidecar_path(
        analysis_dir,
        "routine_logic_details",
        "routine-logic-details.md",
    )
    if routine_markdown_path is not None and routine_markdown_path.is_file():
        findings.extend(
            validate_ordered_headings(
                read_text(routine_markdown_path),
                ROUTINE_FINAL_SECTIONS,
                "routine-logic-details.md",
            )
        )

    for batch_path in batches:
        batch_text = read_text(batch_path)
        batch_label = str(batch_path.relative_to(analysis_dir))
        window_ids = batch_assigned_window_ids(batch_text)
        assigned_ids = batch_assigned_rlog_ids(batch_path)
        scope_count = max(len(window_ids), len(assigned_ids))
        if scope_count > 5:
            findings.append(
                f"{batch_label} contains more than 5 deep-read routines/windows ({scope_count})"
            )
        seed_matches = semantic_seed_matches(batch_text)
        if seed_matches:
            findings.append(
                f"{batch_label} still contains pending semantic deep-read content; "
                "complete this retained batch before validation. Matched: "
                + ", ".join(seed_matches)
            )
        findings.extend(
            validate_ordered_h2_headings(
                batch_text,
                BATCH_REQUIRED_SECTIONS,
                batch_label,
            )
        )
        findings.extend(validate_batch_core_has_no_source_snippets(batch_text, batch_label))
        findings.extend(validate_batch_core_has_no_pending_cells(batch_text, batch_label))
        routine_section = h2_section_text(batch_text, "Routine Details")
        findings.extend(
            validate_rlog_block_quality(
                routine_section,
                assigned_ids or None,
                batch_label,
            )
        )
        positions = heading_positions(batch_text)
        if not all(heading in positions for heading in BATCH_CORE_SECTIONS):
            continue
        first_core_position = min(positions[heading] for heading in BATCH_CORE_SECTIONS)
        rlog_match = RLOG_RE.search(batch_text)
        if rlog_match and first_core_position > rlog_match.start():
            findings.append(
                f"{batch_label} must put Calculation/Validation/Exception core logic before per-routine RLOG detail"
            )
    return findings


def validate_sidecar_set(analysis_dir: Path) -> list[str]:
    findings: list[str] = []
    path = summary_path(analysis_dir)
    if path is None or not path.is_file():
        findings.append("Missing required file: <PROGRAM>-program-analysis-summary.yaml")
        return findings

    entries = sidecar_entries_for_dir(analysis_dir)
    for key in CORE_SIDECAR_KEYS:
        entry = entries.get(key)
        if not entry:
            findings.append(f"{path.name} missing sidecar declaration: {key}")
            continue
        rel_path = entry.get("path")
        status = entry.get("status")
        if status != "present":
            findings.append(f"core sidecar {key} must have status present, found {status or 'missing'}")
        if rel_path and not (analysis_dir / rel_path).is_file():
            findings.append(f"declared core sidecar file is missing: {rel_path}")

    for key, entry in entries.items():
        status = entry.get("status", "")
        rel_path = entry.get("path", "")
        if status in {"present", "optional_triggered"} and rel_path and not (analysis_dir / rel_path).is_file():
            findings.append(f"declared sidecar {key} is {status} but file is missing: {rel_path}")

    return findings


def message_inventory_payload(analysis_dir: Path) -> dict[str, Any]:
    path = declared_sidecar_path(
        analysis_dir,
        "message_inventory_yaml",
        "message-inventory.yaml",
    )
    if path is None or not path.is_file():
        return {}
    payload = load_yaml(path)
    inventory = (payload or {}).get("message_inventory", {})
    return inventory if isinstance(inventory, dict) else {}


def message_entries(inventory: dict[str, Any]) -> list[dict[str, Any]]:
    details = inventory.get("details", [])
    if isinstance(details, list) and details:
        return [entry for entry in details if isinstance(entry, dict)]
    summary = inventory.get("summary", [])
    if isinstance(summary, list):
        return [entry for entry in summary if isinstance(entry, dict)]
    return []


def has_unresolved_message_description(entry: dict[str, Any]) -> bool:
    description = str(
        entry.get("short_description")
        or entry.get("message_description")
        or entry.get("description")
        or ""
    ).strip().lower()
    description_source = str(entry.get("description_source") or "").strip().lower()
    evidence_status = str(entry.get("evidence_status") or "").strip().lower()
    if description == UNRESOLVED_MESSAGE_DESCRIPTION:
        return True
    if description_source in UNRESOLVED_DESCRIPTION_SOURCES:
        return True
    if evidence_status in UNRESOLVED_DESCRIPTION_STATUSES:
        return True
    return False


def validate_message_descriptions(analysis_dir: Path) -> list[str]:
    inventory = message_inventory_payload(analysis_dir)
    if not inventory:
        return []
    unresolved = [
        str(entry.get("message") or entry.get("message_code") or entry.get("code") or "unknown")
        for entry in message_entries(inventory)
        if has_unresolved_message_description(entry)
    ]
    unresolved = sorted(set(unresolved))
    if not unresolved:
        return []
    return [
        "message descriptions unresolved for observed message/status/code values: "
        + ", ".join(unresolved)
        + ". Provide message file/catalog/reference pack, source literal/comment, "
        "runtime evidence, or SME-approved descriptions before final delivery."
    ]


def observed_message_codes(analysis_dir: Path) -> list[str]:
    inventory = message_inventory_payload(analysis_dir)
    if not inventory:
        return []
    codes: list[str] = []
    for entry in message_entries(inventory):
        value = entry.get("message") or entry.get("message_code") or entry.get("code")
        if value:
            codes.append(str(value))
    return sorted(set(codes))


def validate_message_inventory_sync(program_markdown: str, analysis_dir: Path) -> list[str]:
    codes = observed_message_codes(analysis_dir)
    if not codes:
        return []

    message_section = h2_section_text(program_markdown, "Message Inventory")
    missing = [code for code in codes if code not in message_section]
    if not missing:
        return []
    return [
        "program-analysis.md Message Inventory missing observed YAML message/code values: "
        + ", ".join(missing)
    ]


def validate(analysis_dir: Path, program_analysis: Path | None = None) -> list[str]:
    findings: list[str] = []
    if not analysis_dir.is_dir():
        return [f"Analysis directory does not exist: {analysis_dir}"]

    program_path = find_program_analysis_path(analysis_dir, program_analysis)
    if program_path is None or not program_path.is_file():
        findings.append("Missing program-analysis.md or a single program-analysis-<OBJ-ID>.md")
    else:
        program_markdown = read_text(program_path)
        findings.extend(validate_required_sections(program_markdown))
        findings.extend(validate_program_rlog_coverage(program_markdown, analysis_dir))
        findings.extend(validate_core_logic_routine_indexes(program_markdown, analysis_dir))
        findings.extend(validate_reader_first_golden_gate(program_markdown, analysis_dir))
        findings.extend(validate_no_stale_gap_wording(program_markdown))
        findings.extend(validate_message_inventory_sync(program_markdown, analysis_dir))

    findings.extend(validate_sidecar_set(analysis_dir))
    findings.extend(validate_rlog_coverage(analysis_dir))
    findings.extend(validate_routine_yaml_semantic_completion(analysis_dir))
    findings.extend(validate_batch_yaml_semantic_completion(analysis_dir))
    findings.extend(validate_consolidated_routine_semantic_completion(analysis_dir))
    findings.extend(validate_large_program_batches(analysis_dir))
    findings.extend(validate_routine_detail_review_surfaces(analysis_dir))
    findings.extend(validate_message_descriptions(analysis_dir))
    return findings


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Validate legacy-ibmi-program-analyzer artifact contract completeness."
    )
    parser.add_argument("--analysis-dir", type=Path, required=True)
    parser.add_argument("--program-analysis", type=Path, default=None)
    args = parser.parse_args(argv)

    try:
        findings = validate(args.analysis_dir, args.program_analysis)
    except RuntimeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    if findings:
        for finding in findings:
            print(f"ERROR: {finding}", file=sys.stderr)
        return 1

    print("Program analysis contract validation passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
